app:
  name: Otimizador de computador
  version: 1.0.0
  temporary-folders:
    - ${TEMP}
    - C:/Windows/Temp
    - C:/Windows/Prefetch

cleaner:
  delete-subfolders: true
  max-file-age-days: 7

startup:
  allow-modifications: true